version: "3.9"
services:
  db:
    image: postgres:16
    container_name: drive_db
    environment:
      POSTGRES_USER: drive
      POSTGRES_PASSWORD: drive
      POSTGRES_DB: drive
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drive"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: drive_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready"]

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: drive_keycloak
    command: ["start-dev","--import-realm"]
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-admin}
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import
    ports: ["8081:8080"]

  backend:
    build:
      context: ./backend
    container_name: drive_backend
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg://drive:drive@db:5432/drive
    depends_on:
      - db
      - minio
      - keycloak
    ports: ["8080:8080"]

  web:
    build:
      context: ./web
    container_name: drive_web
    environment:
      NEXT_PUBLIC_OIDC_ISSUER: http://localhost:8081/realms/drive
      NEXT_PUBLIC_OIDC_CLIENT_ID: drive-web
      NEXT_PUBLIC_API_BASE: http://localhost:8080
    depends_on:
      - backend
    ports: ["3000:3000"]

volumes:
  minio-data:
